blank_issues_enabled: false
contact_links:
  - name: 提问
    url: https://github.com/DZX66/cyberworld/discussions/new?category=%E6%8F%90%E9%97%AE
    about: 我不想提交反馈，只是想问一些问题
  - name: 讨论
    url: https://github.com/DZX66/cyberworld/discussions/new?category=%E4%B8%80%E8%88%AC%E8%AE%A8%E8%AE%BA
    about: 我不想提交反馈也不想问问题，只是想讨论些 cyberworld 相关的事情